### ISSUE TITLE
UserEntity Birth 요소의 타입 변경

### ISSUE THREAD

**Issue by 98StarJune** [Deep-Caffeine/Server#41]
## 개요
UserEntity의 Birth 요소가 Date 형식이 아닌 string으로 설정되어 있습니다.

## 수정 요청
- [ ] Birth : String -> Date

## 추가 검토
Phone은 string이 맞나요?

**Comment by yejun614** [comment]
Phone은 sring으로 해도 괜찮을 거에요. Birth의 경우에는 Date객체를 사용하는데 DB 쿼리 보낼때나 저희가 코드를 작성하기에도 훨씬 편리해서 변경하는게 좋구요.
